In [2]:
import pandas as pd
import numpy as np

In [7]:
r = int(input('radius'))
b = 2*3.14*r*r
print('circumference:',b)

radius 2


circumference: 25.12


## 4 DataTypes

- list
- tuple
- set
- dict

### List

In [8]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [9]:
a[2:3]

[3]

In [10]:
a.append(6)
a

[1, 2, 3, 4, 5, 6]

In [11]:
a.pop()

6

In [12]:
a

[1, 2, 3, 4, 5]

In [13]:
a.insert(3,'jith')

In [14]:
a

[1, 2, 3, 'jith', 4, 5]

In [15]:
a.remove('jith')

In [16]:
a

[1, 2, 3, 4, 5]

### Tuple

In [17]:
a = (1,2,3,4,5,6)
a

(1, 2, 3, 4, 5, 6)

In [18]:
type(a)

tuple

In [19]:
len(a)

6

In [20]:
a.pop()

AttributeError: 'tuple' object has no attribute 'pop'

In [21]:
a[0]

1

In [23]:
a[::]

(1, 2, 3, 4, 5, 6)

In [24]:
a[:3]

(1, 2, 3)

### Set

In [25]:
a = {1,2,3,4,5,6}
a

{1, 2, 3, 4, 5, 6}

In [26]:
type(a)

set

In [27]:
a.add(5)

In [28]:
a

{1, 2, 3, 4, 5, 6}

In [29]:
a.remove(5)

In [30]:
a

{1, 2, 3, 4, 6}

In [31]:
a.clear()
a

set()

In [32]:
a.update({10,11,2})
a

{2, 10, 11}

### Dictionary

In [33]:
a = {'Name':'Jithendra',
     'ph.no':6300696935,
     'city':'Nandyal'}
a

{'Name': 'Jithendra', 'ph.no': 6300696935, 'city': 'Nandyal'}

In [34]:
type(a)

dict

In [35]:
a['Name']

'Jithendra'

In [36]:
a['Name'] = 'Kedhar'
a

{'Name': 'Kedhar', 'ph.no': 6300696935, 'city': 'Nandyal'}

In [37]:
a['city'].append('Nandyala')
a

AttributeError: 'str' object has no attribute 'append'

In [38]:
a = {'Name':'Jithendra',
     'ph.no':6300696935,
     'city':['Nandyal']}
a

{'Name': 'Jithendra', 'ph.no': 6300696935, 'city': ['Nandyal']}

In [39]:
a['city'].append('Nandyala')
a

{'Name': 'Jithendra', 'ph.no': 6300696935, 'city': ['Nandyal', 'Nandyala']}

In [40]:
a.pop('Name')
a

{'ph.no': 6300696935, 'city': ['Nandyal', 'Nandyala']}

In [43]:
a['city'].pop(0)
a

{'ph.no': 6300696935, 'city': ['Nandyala']}

In [44]:
a['city'][0] = 'Nandyal'
a

{'ph.no': 6300696935, 'city': ['Nandyal']}

## CONDITIONS

## >, <, >=, <=, ==, !=, AND, OR

In [46]:
(100==100)|(100==99)

True

In [48]:
a = 99
b = 100

if a>b:
    print("a is greater than b")
elif a<b:
    print("a is less than b")
else:
    print("a can equal to or less than b")

    

a is less than b


## LOOPS

## for and while

In [49]:
for i in range(0,4,1):
    print(i)

0
1
2
3


In [50]:
for i in [1,2,3]:
    print(5*i)

5
10
15


In [51]:
for i in (1,2,3):
    print(5*i)

5
10
15


In [53]:
i = 5

while i>1:
    print(i)
    i=i-1

5
4
3
2


## FUNCTIONS

In [59]:
def printing(a):
    try:
        print("given value:",a)
    except Exception as e:
        return ("Calculated value:", a*5)

printing(5)

given value: 5


## NUMPY

In [60]:
import numpy as np

In [63]:
np.around(np.pi,3)

3.142

In [64]:
np.round(np.pi,3)

3.142

In [65]:
np.sqrt(25)

5.0

In [66]:
np.log(10)

2.302585092994046

In [68]:
np.log10(100)

2.0

In [69]:
np.exp(1)

2.718281828459045

In [70]:
np.ceil(3.6)

4.0

In [72]:
np.floor(3.6)

3.0

In [76]:
np.random.rand()

0.8364131046345452

In [77]:
a = np.random.rand(10)
a

array([0.26812893, 0.27894609, 0.67746668, 0.60936646, 0.88926823,
       0.76334041, 0.47510337, 0.60324038, 0.80094593, 0.23620811])

In [78]:
a.min()

0.2362081077389817

In [79]:
a.max()

0.8892682282130244

In [80]:
a.mean()

0.5602014572426033

In [81]:
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [82]:
a.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

## Ndarrays

In [85]:
a = np.arange(0,10,1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a.dtype

dtype('int32')

In [88]:
type(a)

numpy.ndarray

In [89]:
a.shape

(10,)

In [92]:
b = np.linspace(1,10,19)
b

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [93]:
np.array(b)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [94]:
b[:]

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [95]:
b[0:2]

array([1. , 1.5])

In [96]:
b[::2]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [97]:
b[::-2]

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

In [98]:
b[::]

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [99]:
b[2::]

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [100]:
b[2:]

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [101]:
b[2:0:1]

array([], dtype=float64)

In [102]:
b[2:10:1]

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [103]:
c = [1,2,3,4,'jith']
c

[1, 2, 3, 4, 'jith']

In [105]:
c = np.array(c)
c

array(['1', '2', '3', '4', 'jith'], dtype='<U11')

In [106]:
type(c)

numpy.ndarray

In [107]:
c.dtype

dtype('<U11')

## MATRICES 2D

In [109]:
a = np.random.rand(9)
a

array([0.01236125, 0.5693184 , 0.37311187, 0.7786943 , 0.63654727,
       0.04384961, 0.23880047, 0.5775088 , 0.54917714])

In [112]:
a.reshape(3,3)

array([[0.01236125, 0.5693184 , 0.37311187],
       [0.7786943 , 0.63654727, 0.04384961],
       [0.23880047, 0.5775088 , 0.54917714]])

In [114]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
np.arange(0,27,1).reshape(3,3,3).T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [124]:
a=np.array([[1,2,3,4],[5,6,7,8]]).T
a

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [125]:
a.values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [126]:
a.index

AttributeError: 'numpy.ndarray' object has no attribute 'index'

## Pandas Series

In [127]:
import pandas as pd

In [128]:
a = pd.Series([1,2,3,4,5,6])
a

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [129]:
type(a)

pandas.core.series.Series

In [131]:
a.values

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [132]:
a.index

RangeIndex(start=0, stop=6, step=1)

In [137]:
np.random.rand(10)

array([0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578])

In [135]:
np.random.seed(10)

In [138]:
a.index = ['1st','2nd','3rd','4th','5th','6th']
a

1st    1
2nd    2
3rd    3
4th    4
5th    5
6th    6
dtype: int64

In [139]:
a = pd.Series([1,2],index=['first','second'])
a

first     1
second    2
dtype: int64

In [144]:
b = a.dtype

In [145]:
b

dtype('int64')

In [147]:
dict = {'Name':['jithendra','Kedhar','sai'], 'City':['Nandyal','Kurnool','Andhra']}
dict

{'Name': ['jithendra', 'Kedhar', 'sai'],
 'City': ['Nandyal', 'Kurnool', 'Andhra']}

In [148]:
a = pd.DataFrame(dict)
a

Name     City
0  jithendra  Nandyal
1     Kedhar  Kurnool
2        sai   Andhra

In [149]:
a = pd.DataFrame(['1st','2nd','3rd','4th','5th','6th'])
a

0
0  1st
1  2nd
2  3rd
3  4th
4  5th
5  6th

In [152]:
a = pd.DataFrame(dict,index=['1st','2nd','3rd'],columns=['col1','col2'])
a

col1 col2
1st  NaN  NaN
2nd  NaN  NaN
3rd  NaN  NaN

In [153]:
import os
os.getcwd()

'C:\\Users\\gjithend\\Desktop\\HTML_PROJECT\\ALL_FOLDERS\\LEARNINGS\\LEARNINGS\\STATISTICS_FOR_DATASCIENCE'

In [154]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../PANDAS/PANDAS_DATAFRAME_PRACTICE1.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	./

no changes added to commit (use "git add" and/or "git commit -a")


In [156]:
!git add .

In [158]:
!git commit -m "Basic Python added"

[main 86f297b] Basic Python added
 2 files changed, 2466 insertions(+)
 create mode 100644 STATISTICS_FOR_DATASCIENCE/.ipynb_checkpoints/BASIC_PYTHON-checkpoint.ipynb
 create mode 100644 STATISTICS_FOR_DATASCIENCE/BASIC_PYTHON.ipynb


In [159]:
!git push

To github.com:gali-jithendra/LEARNINGS.git
   78d5dcc..86f297b  main -> main
